### ISSUE TITLE
Error : Not supported toDD

### ISSUE THREAD

**Issue by thevpc** [thevpc/scholar-mw#1]
Exception in thread "main" java.lang.UnsupportedOperationException: Not supported toDD
	at net.vpc.scholar.hadrumaths.symbolic.AbstractDoubleToMatrix.toDD(AbstractDoubleToMatrix.java:89)
	at net.vpc.scholar.hadrumaths.symbolic.Any.toDD(Any.java:263)
	at net.vpc.scholar.hadrumaths.scalarproducts.MatrixScalarProductCache$2.invoke(MatrixScalarProductCache.java:148)
	at net.vpc.scholar.hadrumaths.util.VoidMonitoredAction.process(VoidMonitoredAction.java:8)
	at net.vpc.scholar.hadrumaths.util.VoidMonitoredAction.process(VoidMonitoredAction.java:6)
	at net.vpc.scholar.hadrumaths.ProgressMonitorFactory.invokeMonitoredAction(ProgressMonitorFactory.java:267)
	at net.vpc.scholar.hadrumaths.Maths.invokeMonitoredAction(Maths.java:5010)
	at net.vpc.scholar.hadrumaths.scalarproducts.MatrixScalarProductCache.evaluate(MatrixScalarProductCache.java:133)
	at net.vpc.scholar.hadrumaths.Maths.scalarProductCache(Maths.java:3761)
	at net.vpc.scholar.hadrumaths.scalarproducts.ScalarProductOperator.eval(ScalarProductOperator.java:82)
	at net.vpc.scholar.hadruwaves.mom.MomStructure.createScalarProductCache(MomStructure.java:1719)
	at net.vpc.scholar.hadruwaves.mom.FnGpScalarProductCacheStrCacheSupport.compute(FnGpScalarProductCacheStrCacheSupport.java:25)
	at net.vpc.scholar.hadruwaves.mom.FnGpScalarProductCacheStrCacheSupport.compute(FnGpScalarProductCacheStrCacheSupport.java:11)
	at net.vpc.scholar.hadrumaths.cache.CacheSupport$1$1.evaluate(CacheSupport.java:67)
	at net.vpc.scholar.hadrumaths.cache.PersistenceCache$3.call(PersistenceCache.java:574)
	at net.vpc.scholar.hadrumaths.util.AbstractAppLock.invoke(AbstractAppLock.java:89)
	at net.vpc.scholar.hadrumaths.cache.PersistenceCache.evaluate(PersistenceCache.java:546)
	at net.vpc.scholar.hadrumaths.cache.CacheSupport$1.process(CacheSupport.java:59)
	at net.vpc.scholar.hadrumaths.ProgressMonitorFactory.invokeMonitoredAction(ProgressMonitorFactory.java:267)
	at net.vpc.scholar.hadrumaths.Maths.invokeMonitoredAction(Maths.java:5010)
	at net.vpc.scholar.hadrumaths.cache.CacheSupport.computeCached(CacheSupport.java:46)
	at net.vpc.scholar.hadruwaves.mom.StrCacheSupport.get(StrCacheSupport.java:21)
	at net.vpc.scholar.hadruwaves.mom.MomStructure.getTestModeScalarProducts(MomStructure.java:1278)
	at net.vpc.scholar.hadruwaves.mom.ZinMatrixStrCacheSupport.init(ZinMatrixStrCacheSupport.java:23)
	at net.vpc.scholar.hadrumaths.cache.CacheSupport$1$1.init(CacheSupport.java:62)
	at net.vpc.scholar.hadrumaths.cache.PersistenceCache$3.call(PersistenceCache.java:571)
	at net.vpc.scholar.hadrumaths.util.AbstractAppLock.invoke(AbstractAppLock.java:89)
	at net.vpc.scholar.hadrumaths.cache.PersistenceCache.evaluate(PersistenceCache.java:546)
	at net.vpc.scholar.hadrumaths.cache.CacheSupport$1.process(CacheSupport.java:59)
	at net.vpc.scholar.hadrumaths.ProgressMonitorFactory.invokeMonitoredAction(ProgressMonitorFactory.java:267)
	at net.vpc.scholar.hadrumaths.Maths.invokeMonitoredAction(Maths.java:5010)
	at net.vpc.scholar.hadrumaths.cache.CacheSupport.computeCached(CacheSupport.java:46)
	at net.vpc.scholar.hadruwaves.mom.StrCacheSupport.get(StrCacheSupport.java:21)
	at net.vpc.scholar.hadruwaves.mom.DefaultInputImpedanceBuilder.computeMatrixImpl(DefaultInputImpedanceBuilder.java:19)
	at net.vpc.scholar.hadruwaves.builders.AbstractComplexBuilder$1.process(AbstractComplexBuilder.java:31)
	at net.vpc.scholar.hadruwaves.builders.AbstractComplexBuilder$1.process(AbstractComplexBuilder.java:28)
	at net.vpc.scholar.hadrumaths.ProgressMonitorFactory.invokeMonitoredAction(ProgressMonitorFactory.java:267)
	at net.vpc.scholar.hadrumaths.Maths.invokeMonitoredAction(Maths.java:5010)
	at net.vpc.scholar.hadruwaves.builders.AbstractComplexBuilder.computeMatrixImplLog(AbstractComplexBuilder.java:28)
	at net.vpc.scholar.hadruwaves.builders.AbstractComplexBuilder.computeComplexImpl(AbstractComplexBuilder.java:37)
	at net.vpc.scholar.hadruwaves.builders.AbstractComplexBuilder.computeComplex(AbstractComplexBuilder.java:58)
	at thesis.projects.thesisprojects.MoMPatchEEEE.v310.d_2017_07_26_PatchDEA1_ParamVariation_verifV1$.$anonfun$main$5(d_2017_07_26_PatchDEA1_ParamVariation_verifV1.scala:128)
	at thesis.projects.thesisprojects.MoMPatchEEEE.v310.d_2017_07_26_PatchDEA1_ParamVariation_verifV1$$$Lambda$42/757004314.run(Unknown Source)
	at net.vpc.scholar.hadrumaths.AbstractTVector.forEachIndex(AbstractTVector.java:849)
	at thesis.projects.thesisprojects.MoMPatchEEEE.v310.d_2017_07_26_PatchDEA1_ParamVariation_verifV1$.$anonfun$main$2(d_2017_07_26_PatchDEA1_ParamVariation_verifV1.scala:126)
	at thesis.projects.thesisprojects.MoMPatchEEEE.v310.d_2017_07_26_PatchDEA1_ParamVariation_verifV1$$$Lambda$39/1891546521.apply$mcVI$sp(Unknown Source)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofInt.foreach(ArrayOps.scala:239)
	at thesis.projects.thesisprojects.MoMPatchEEEE.v310.d_2017_07_26_PatchDEA1_ParamVariation_verifV1$.$anonfun$main$1(d_2017_07_26_PatchDEA1_ParamVariation_verifV1.scala:75)
	at thesis.projects.thesisprojects.MoMPatchEEEE.v310.d_2017_07_26_PatchDEA1_ParamVariation_verifV1$$$Lambda$38/520022247.apply$mcVI$sp(Unknown Source)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofInt.foreach(ArrayOps.scala:239)
	at thesis.projects.thesisprojects.MoMPatchEEEE.v310.d_2017_07_26_PatchDEA1_ParamVariation_verifV1$.main(d_2017_07_26_PatchDEA1_ParamVariation_verifV1.scala:69)
	at thesis.projects.thesisprojects.MoMPatchEEEE.v310.d_2017_07_26_PatchDEA1_ParamVariation_verifV1.main(d_2017_07_26_PatchDEA1_ParamVariation_verifV1.scala)

**Comment by thevpc** [comment]
this issue is related to the fact that the two elements to compute are not of the same dimension; one cannot run a scalar product of a scalar and a vector.
